"""create documents table

Revision ID: 5cbd94f882b4
Revises: 
Create Date: 2026-05-29 13:21:09.900846

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cbd94f882b4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('contextual_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
